### ISSUE TITLE
Pinning versions in git dependencies

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#107]
We often use git dependencies in `Cargo.toml`. Considering our use case, I think that is quite fine. However, I do think we should start to add tags (or releases) to those repos and pin these in `Cargo.toml`. This is necessary in order to be able to update/alter our dependencies during development without breaking the current releases of Brane. This is particularly important with dependencies that see active development, like `policy-reasoner`

Alternatively, we could look into pinning the latest commit of everything during releasing to either a commit or tag and keep it loose during the development phases.

All in all, we have to strike a balance between the cost of upkeep on one hand and not breaking existing releases on the other.

**Comment by Lut99** [comment]
Makes sense. I think that my pet projects -`enum-debug`, `humanlog`, `error-trace`, etc- have tags, so feel free to add them. Let me know if any more are added.

Then I agree that a release of `policy-reasoner` is soon coming once we've set implemented the current round of features that make it work. We can then commit `brane` to that version of the policy reasoner.

**Comment by DanielVoogsgerd** [comment]
State:
- [ ] Enum-debug: Last commit has not been tagged
- [ ] Download-rs: 
- [ ] Error-trace-rs:
- [ ] humanlog-rs:
- [ ] names-rs:
- [ ] socksx:
- [ ] cwl-rs:

**Comment by DanielVoogsgerd** [comment]
@lut99, could you add tags for the missing deps, so I can wrap this up?

**Comment by Lut99** [comment]
Lol, ah well you already treated my comment I made elsewhere xD great!

Yes I'll look at it. I'll report back once done.

**Comment by Lut99** [comment]
OK, try it now!

P.S. Does the policy reasoner need to be on this list too?

**Comment by DanielVoogsgerd** [comment]
Yes, but also no. Policy reasoner should definitely be tagged when we do a release again, but considering the amount of work we are still performing on the Policy Reasoner, I would not use the tag myself.

The entire Brane repo / Policy Reasoner repo dynamic is going to be a bit weird, at least until we stabilize. Especially considering it is also using the Dockerfile inside the Brane repo (which I have constantly modified to point to different branches on my fork). If the policy reasoner becomes very stable I don't see much of an issue, if this continues to be an active part of the development, this is probably going to be a headache, but lets see what happens. If it becomes too cumbersome, I'll open up an issue again.

**Comment by Lut99** [comment]
Yeah... well, if you have ideas to improve the interaction, don't hesitate to bring them up. I agree it's very awkward (especially because they cross-reference each other!).

Maybe there's some stuff of Brane we can publish on crates.io? Probably at least `specifications` and maybe the `brane-ast`-stack, if the reasoner depends on it. Then at the very least, they will have a common ancestor instead of being cyclic. Maybe that'll help?

**Comment by DanielVoogsgerd** [comment]
I am not sure about publishing on crates.io until we are a bit more beta than alpha. I am still considering suggesting dropping the version numbers to pre-1.0 which is impossible in the case of crates.io. All in all, a bit more project maturity might be nice before we do that.

**Comment by Lut99** [comment]
OK, fair enough. Still, if either of us happens to stumble upon some organisational trick for the `policy-reasoner` link, don't hesitate to bring it up :)
