### ISSUE TITLE
branectl logs

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#112]
When something goes wrong in one of the containers, I find myself constantly going thought all the different docker images using `docker log`. Normally, I would use `docker-compose logs -f <compose-file>`, but this is not really possible as there are a lot of environment variables that I think branectl fills in during `branectl start ...`. Maybe, we can create something like `branectl logs` which wraps `docker-compose` and fills in the relevant env vars as well. Especially combined with a `-f` follow flag, this could help debugging the system.

The clear alternative for such purposes would be something like OpenTelemetry, but this could be overkill and could cause its own troubles, of course.

**Comment by Lut99** [comment]
Very good idea! Seems like a perfect fit for the diagnose-plans you had!
