### ISSUE TITLE
Fixing Rust version in containers

### ISSUE THREAD

**Issue by Lut99** [epi-project/brane#115]
While testing #114, I noticed that Docker automatically pulls the most up-to-date version of Rust to build the service binaries with. Of course, it can sometimes happen that newer versions of Rust introduce breaking changes (e.g., because of warnings lints becoming errors ~ <https://github.com/epi-project/brane-documentation/issues/23#issuecomment-2245422550>). So do we want to fix to a particular version?

You could argue nothing should break in principle, and the example is definitely a case we were relying on already deprecated behavior. Still, would it make sense to try avoid compilation errors? Or do we prefer updating the Rust version automatically?

**Comment by DanielVoogsgerd** [comment]
Ghmm, I am really torn on this issue. Given a defined Rust edition. Rust should always be backwards compatible in principle, I am still not entirely sure what happened in your example, as the first time I compiled Brane is -- I think -- just about the first time this issue showed up. When this project is actively maintained, the nightly builds are there for this precise reason, as they function as an early warning sign if something is going to be broken in the future.

All in all, I think this effort is best focussed on keeping CI green and trusting the language not to break its promise to stay backwards compatible.

**Comment by Lut99** [comment]
All true ~ and like I said, the breaking change came from me relying on deprecated behaviour in the first place and being like "I'll deal with it later" xD

To play the devil's advocate, though, are we OK with relying on Rust to not break its promise if we intend the project to survive an extended period of hibernation? There might be a time that neither of us is here, so it could be that the warnings are there but nobody will pick up on them. It's the same discussion as with any dependency, I reckon...

Maybe making it dynamic would be an option. Like, is it possible to default to the latest version(s) but define a minimum version (like the other dependencies) and then have some flag that users can use to force `cargo` and `make.py` to select those instead? Then we can very clearly document "in case of errors, try this first" for longevity purposes.

**Comment by DanielVoogsgerd** [comment]
I think that is kinda what MSRV is supposed to convey. I think they stay closely enough to this promise to not cause too much of an issue. What you could do is mention the last version of Rust this was tested on, but this come with a small cost of ~1 commit per ~6 weeks.

If somebody ever picks up this project again; I think they have bigger problems than using rustup to select an old rust version :sweat_smile:. Let's say I expect packages to break backwards compatiblity more often than the language itself.

**Comment by Lut99** [comment]
Lmao. OK, let's not pin it then.

But let's do it like this: we should make a troubleshooting section somewhere (if we hadn't already) and mention this first. I know it would've helped me the first time I got it on my lap :)
