### ISSUE TITLE
Minmax examples

### ISSUE THREAD

**Issue by DanielVoogsgerd** [epi-project/brane#75]
The file [container.yml](https://github.com/epi-project/brane/blob/develop/examples/doc/minmax/container.yml) in the minmax example seems to be empty and it's code.py neighbour as well. Shall we remove this or is there an implementation that can be committed?

**Comment by Lut99** [comment]
Ah, this used to be part of the docs for scientist. I think we can remove it, those have to be rewritten anyway.
